# Generated by Django 4.2.2 on 2023-08-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='created_at',
        ),
    ]
