# Generated by Django 4.2.2 on 2023-08-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0003_remove_advertisement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
